<?php


namespace Carsdaq\Notice\IOS;


use Carsdaq\Notice\Exception\UmengException;
use Carsdaq\Notice\IOSNativeCode;

class IOSNative extends IOSNativeCode
{
    function __construct($data)
    {
        parent::__construct();
        $this->data = $data;

    }

    function setParam()
    {
        parent::setParam(); // TODO: Change the autogenerated stub
    }

    public function setProductionMode($production_mode)
    {
        parent::setProductionMode($production_mode); // TODO: Change the autogenerated stub

    }

    public function setPathPem($pathPem)
    {
        parent::setPathPem($pathPem); // TODO: Change the autogenerated stub
    }

    function isComplete()
    {
        parent::isComplete(); // TODO: Change the autogenerated stub
        if (!is_file($this->pemPath)) {
            \Log::error("证书不存在");
            throw new UmengException("证书文件不存在，请检查文件权限或路径是否正确");
        }
    }


}